### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isoformat'`

### ISSUE THREAD

**Issue by WegnerDan** [muffix/byImpf#1]
`PS C:\Users\thedo\Downloads\byImpf-main> python impf.py --citizen-id=ID --email=email --password=pw
Traceback (most recent call last):
  File "C:\Users\thedo\Downloads\byImpf-main\impf.py", line 320, in <module>
    checker.find(earliest_day=args.earliest_day.isoformat(), book=args.book)
AttributeError: 'NoneType' object has no attribute 'isoformat'`

I have special characters in my password, maybe that's the problem. I also tried putting the password in double quotes ("pw").

With the parameter "--earliest-day" it returns "No appointment available"

**Comment by muffix** [comment]
Thanks @thedoginthewok, I should probably clarify the docs.

`--earliest-day` expects the earliest acceptable date as a parameter. It cannot be blank. So if the option is present, it must have a value.
So if you run it with something like `--earliest-day=2021-12-24`, the script will search for appointments from 24 December 2021. You can leave out `--earliest-day` entirely to find the soonest available appointment.

**Comment by WegnerDan** [comment]
I got that, it's just that leaving out the earliest-day parameter leads to an error instead of looking for the soonest available appointment. It only looks for appointments, if I include it.

**Comment by muffix** [comment]
What's the error you're getting? If it's "No appointment available", that's the vaccination centre being fully booked.

**Comment by WegnerDan** [comment]
The error is in the first message in this issue.
`Traceback (most recent call last): File "C:\Users\thedo\Downloads\byImpf-main\impf.py", line 320, in <module> checker.find(earliest_day=args.earliest_day.isoformat(), book=args.book) AttributeError: 'NoneType' object has no attribute 'isoformat'`

**Comment by muffix** [comment]
Got it now. I think I broke it between rebases. 😅Fixed in https://github.com/muffix/byImpf/commit/d87065a1410893e7a51f2e87ad83a974e40c043b.
